/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProductManagement;

import BillManagement.BanHang;
import BillManagement.QL_HoaDon;
import Connect.JDBCDatabase;
import HomePage.HomeEmployee;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author ThinkPad
 */
public class QL_SanPham extends javax.swing.JFrame {

    /**
     * Creates new form QL_SanPham
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    Statement st = null;
    public QL_SanPham(){
        initComponents();
        try{
            con = JDBCDatabase.getConnection();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        DisplayDM();
        DisplayTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jLabel246 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        jPanel55 = new javax.swing.JPanel();
        textGB = new javax.swing.JTextField();
        jLabel235 = new javax.swing.JLabel();
        spAdd = new javax.swing.JButton();
        spUpdate = new javax.swing.JButton();
        spDelete = new javax.swing.JButton();
        textSL = new javax.swing.JTextField();
        jLabel237 = new javax.swing.JLabel();
        textTNCC = new javax.swing.JTextField();
        jLabel238 = new javax.swing.JLabel();
        textTSP = new javax.swing.JTextField();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jLabel241 = new javax.swing.JLabel();
        textDVT = new javax.swing.JTextField();
        jLabel242 = new javax.swing.JLabel();
        textHBH = new javax.swing.JTextField();
        cboDM = new javax.swing.JComboBox<>();
        textMSP = new javax.swing.JTextField();
        jLabel243 = new javax.swing.JLabel();
        spAdd1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel244 = new javax.swing.JLabel();
        searchDM = new javax.swing.JComboBox<>();
        jLabel245 = new javax.swing.JLabel();
        searchName = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();

        jCheckBox1.setText("jCheckBox1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sản Phẩm");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(999, 600));

        jPanel56.setBackground(new java.awt.Color(255, 255, 255));

        jPanel57.setBackground(new java.awt.Color(153, 255, 153));

        jLabel246.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel246.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel246.setText("Danh Sách Thông Tin Sản Phẩm");

        ProductTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Tên Nhà CC", "Giá Bán", "Số Lượng", "Đơn Vị Tính", "Hạn Bảo Hành", "Mã Danh Mục"
            }
        ));
        ProductTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProductTable.setRowHeight(40);
        ProductTable.setSelectionBackground(new java.awt.Color(51, 51, 255));
        ProductTable.setShowGrid(true);
        ProductTable.setSurrendersFocusOnKeystroke(true);
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);
        if (ProductTable.getColumnModel().getColumnCount() > 0) {
            ProductTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel246)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel57Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel246, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel55.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản Phẩm"));

        textGB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textGB.setMargin(new java.awt.Insets(2, 10, 2, 6));

        jLabel235.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel235.setText("Hạn Bảo Hành: ");

        spAdd.setBackground(new java.awt.Color(153, 255, 255));
        spAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        spAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        spAdd.setText("Thêm");
        spAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        spAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spAddActionPerformed(evt);
            }
        });

        spUpdate.setBackground(new java.awt.Color(153, 255, 255));
        spUpdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        spUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        spUpdate.setText("Cập nhật");
        spUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        spUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spUpdateMouseClicked(evt);
            }
        });

        spDelete.setBackground(new java.awt.Color(153, 255, 255));
        spDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        spDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        spDelete.setText("Xóa");
        spDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        spDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spDeleteActionPerformed(evt);
            }
        });

        textSL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textSL.setMargin(new java.awt.Insets(2, 10, 2, 6));

        jLabel237.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel237.setText("Mã Sản Phẩm: ");

        textTNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textTNCC.setMargin(new java.awt.Insets(2, 10, 2, 6));

        jLabel238.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel238.setText("Tên Sản Phẩm: ");

        textTSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textTSP.setMargin(new java.awt.Insets(2, 10, 2, 6));

        jLabel239.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel239.setText("Giá bán: ");

        jLabel240.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel240.setText("Số lượng: ");

        jLabel241.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel241.setText("Danh Mục Sản Phẩm: ");

        textDVT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textDVT.setMargin(new java.awt.Insets(2, 10, 2, 6));

        jLabel242.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel242.setText("Tên Nhà Cung Cấp: ");

        textHBH.setAlignmentX(20.0F);
        textHBH.setMargin(new java.awt.Insets(2, 10, 2, 6));

        cboDM.setAlignmentX(20.0F);
        cboDM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textMSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textMSP.setDisabledTextColor(new java.awt.Color(0, 204, 204));
        textMSP.setMargin(new java.awt.Insets(2, 10, 2, 6));

        jLabel243.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel243.setText("Đơn Vị Tính: ");

        spAdd1.setBackground(new java.awt.Color(255, 51, 51));
        spAdd1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        spAdd1.setForeground(new java.awt.Color(255, 255, 255));
        spAdd1.setText("+");
        spAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addComponent(jLabel241)
                        .addGap(29, 29, 29)
                        .addComponent(cboDM, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spAdd1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel237)
                            .addComponent(jLabel238)
                            .addComponent(jLabel242))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTNCC)
                            .addComponent(textTSP)
                            .addComponent(textMSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addComponent(jLabel239)
                                .addGap(42, 42, 42)
                                .addComponent(textGB))
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel243)
                                    .addComponent(jLabel240))
                                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel55Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(textDVT))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textSL, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel235)
                        .addGap(18, 18, 18)
                        .addComponent(textHBH, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addGap(190, 190, 190))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(spUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(spDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel241)
                        .addComponent(spAdd1))
                    .addComponent(cboDM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel237)
                    .addComponent(jLabel239)
                    .addComponent(textGB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMSP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel238)
                        .addComponent(jLabel240)
                        .addComponent(textTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel243)
                        .addComponent(jLabel242)
                        .addComponent(textDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel235)
                    .addComponent(textHBH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(spUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel244.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel244.setText("Danh Mục Sản Phẩm: ");

        searchDM.setAlignmentX(20.0F);
        searchDM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDMActionPerformed(evt);
            }
        });

        jLabel245.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel245.setText("Nhập tên nhà cung cấp");

        searchName.setAlignmentX(20.0F);
        searchName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchName.setMargin(new java.awt.Insets(2, 10, 2, 6));

        search.setBackground(new java.awt.Color(153, 255, 255));
        search.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        search.setText("Tìm ");
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });

        reset.setBackground(new java.awt.Color(153, 255, 255));
        reset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset.png"))); // NOI18N
        reset.setText("Hủy");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel245)
                            .addComponent(jLabel244)
                            .addComponent(searchName)
                            .addComponent(searchDM, 0, 211, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel244)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchDM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel245)
                .addGap(18, 18, 18)
                .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jMenu1.setText("Quản Lý");

        jMenuItem4.setText("Bán Hàng");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Hóa Đơn");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Báo Cáo");
        jMenuBar1.add(jMenu6);

        Exit.setText("Thoát");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void DisplayTable(){
        try{
            st = con.createStatement();
            rs = st.executeQuery("Select * from productmanagement");
            ProductTable.setModel(DbUtils.resultSetToTableModel(rs));
            String[] header = {"Mã sản phẩm", "Tên sản phẩm","Nhà cung cấp","Giá bán","Số lượng","Đơn vị tính","Hạn bảo hành", "Mã danh mục"};
            TableColumnModel tcm = (TableColumnModel)ProductTable.getColumnModel();
            for(int i=0; i<header.length; i++){
                TableColumn title = tcm.getColumn(i);
                title.setHeaderValue(header[i]);
            }
            ProductTable.getTableHeader().repaint();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new QL_HoaDon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new BanHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void spAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spAddActionPerformed
        // TODO add your handling code here:
        if(textMSP.getText().isEmpty() || textTSP.getText().isEmpty() || textTNCC.getText().isEmpty() || textGB.getText().isEmpty() || textSL.getText().isEmpty() || textDVT.getText().isEmpty() || textHBH.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Dữ liệu không được để trống", "Thông Báo", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                ps = con.prepareStatement("insert into productmanagement values(?, ?, ?, ?, ?, ?, ?, ?)");
                PreparedStatement ps1 = con.prepareStatement("select MaDM from productportfolio where TenDM = ?");
                ps1.setString(1, cboDM.getSelectedItem().toString());
                rs = ps1.executeQuery();
                String maDM = null;
                if(rs.next()){
                    maDM = rs.getString("MaDM");
                }
                ps.setString(1, textMSP.getText());
                ps.setString(2, textTSP.getText());
                ps.setString(3, textTNCC.getText());
                ps.setDouble(4, Double.parseDouble(textGB.getText()));
                ps.setInt(5, Integer.parseInt(textSL.getText()));
                ps.setString(6, textDVT.getText());
                ps.setString(7, textHBH.getText());
                ps.setString(8, maDM);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Thêm Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                DisplayTable();
                //con.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e, "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_spAddActionPerformed

    private void spAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spAdd1ActionPerformed
        PortfolioManagement pm = new PortfolioManagement();
        pm.setVisible(true);
    }//GEN-LAST:event_spAdd1ActionPerformed

    private void spDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spDeleteActionPerformed
        // TODO add your handling code here:
        if(textMSP.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Sản phẩm không tồn tại!");
        }
        else{
            try{
                String id = textMSP.getText();
                String query = "Delete from productmanagement where MaSP= '" + id +"'";
                st = con.createStatement();
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                DisplayTable();
                //con.close();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_spDeleteActionPerformed

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        try{
            DefaultTableModel dtm = (DefaultTableModel)ProductTable.getModel();
            int data = ProductTable.getSelectedRow();
            textMSP.setText(dtm.getValueAt(data, 0).toString());
            textTSP.setText(dtm.getValueAt(data, 1).toString());
            textTNCC.setText(dtm.getValueAt(data, 2).toString());
            textGB.setText(dtm.getValueAt(data, 3).toString());
            textSL.setText(dtm.getValueAt(data, 4).toString());
            textDVT.setText(dtm.getValueAt(data, 5).toString());
            textHBH.setText(dtm.getValueAt(data, 6).toString());
        
            String mdm = dtm.getValueAt(data, 7).toString();
            st = con.createStatement();
            rs = st.executeQuery("Select TenDM from productportfolio where MaDM = '" + mdm + "'");
            String dm = null;
            while(rs.next()){
                dm = rs.getString("TenDM");
            }
            cboDM.setSelectedItem(dm);
        }
        catch(Exception e){
            e.printStackTrace();
        }
             
    }//GEN-LAST:event_ProductTableMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        HomeEmployee hm = new HomeEmployee();
        hm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_ExitMouseClicked

    private void spUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spUpdateMouseClicked
        // TODO add your handling code here:
        if(textMSP.getText().isEmpty() || textTSP.getText().isEmpty() || textTNCC.getText().isEmpty() || textGB.getText().isEmpty() || textSL.getText().isEmpty() || textDVT.getText().isEmpty() || textHBH.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Dữ liệu không được để trống", "Thông Báo", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                String update = "update productmanagement set TenSP = '" + textTSP.getText() + "'"
                                                           + ",TenNCC = '" + textTNCC.getText() + "'"
                                                           + ",GiaBan = '" + textGB.getText() + "'"
                                                           + ",SoLuong = '" + textSL.getText() + "'"
                                                           + ",DonViTinh = '" + textDVT.getText() + "'"
                                                           + ",HanSD = '" + textHBH.getText() + "'"
                                                           + "where MaSP = '" + textMSP.getText() + "'";
                st = con.createStatement();
                st.executeUpdate(update);
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                DisplayTable();
                //con.close();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_spUpdateMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        if(searchName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên nhà cung cấp!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            try{
                String search = "Select * from productmanagement where TenNCC = '" + searchName.getText() + "'";
                st = con.createStatement();
                rs = st.executeQuery(search);
                if(!rs.isBeforeFirst()){
                    JOptionPane.showMessageDialog(this, "Nhà cung cấp không tồn tại", "Thông Báo" ,JOptionPane.INFORMATION_MESSAGE);
                    DisplayTable();
                }
                else{
                     JOptionPane.showMessageDialog(this, "Tìm thành công");
                     ProductTable.setModel(DbUtils.resultSetToTableModel(rs));
                }
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchMouseClicked

    private void searchDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDMActionPerformed
        // TODO add your handling code here:
        try{
            String searchTDM = "Select MaDM from productportfolio where TenDM = '"+ searchDM.getSelectedItem() +"'"; 
            st = con.createStatement();
            rs = st.executeQuery(searchTDM);
            String kq = null;
            while(rs.next()){
                kq = rs.getString("MaDM");
            }
            String searchMDM = "Select * from productmanagement where MaDM ='" + kq + "'";
            rs = st.executeQuery(searchMDM);
            ProductTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchDMActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        cboDM.setSelectedIndex(0);
        textMSP.setText("");
        textTSP.setText("");
        textTNCC.setText("");
        textGB.setText("");
        textSL.setText("");
        textDVT.setText("");
        textHBH.setText("");
        DisplayTable();
    }//GEN-LAST:event_resetActionPerformed

    private void DisplayDM(){
        try{
            st = con.createStatement();
            rs = st.executeQuery("Select TenDM from productportfolio");
        
            ArrayList<String> listDM = new ArrayList<String>();
            while(rs.next()){
                listDM.add(rs.getString("TenDM"));
            }
        
            for(String s : listDM){
                cboDM.addItem(s);
                searchDM.addItem(s);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_SanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Exit;
    private javax.swing.JTable ProductTable;
    private javax.swing.JComboBox<String> cboDM;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel246;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> searchDM;
    private javax.swing.JTextField searchName;
    private javax.swing.JButton spAdd;
    private javax.swing.JButton spAdd1;
    private javax.swing.JButton spDelete;
    private javax.swing.JButton spUpdate;
    private javax.swing.JTextField textDVT;
    private javax.swing.JTextField textGB;
    private javax.swing.JTextField textHBH;
    private javax.swing.JTextField textMSP;
    private javax.swing.JTextField textSL;
    private javax.swing.JTextField textTNCC;
    private javax.swing.JTextField textTSP;
    // End of variables declaration//GEN-END:variables
}
