/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EmployeeManagement.QLNhanVien;

import Account.QL_TaiKhoan;
import ProductManagement.*;
import Connect.*;
import EmployeeManagement.QLLuongNV.QL_Salary;
import HomePage.MenuForQL.HomeManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ThinkPad
 */
public class QL_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QL_SanPham
     */
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    public QL_NhanVien() {
        
        initComponents();
        try{
            con = JDBCDatabase.getConnection();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        DisplayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jLabel246 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableemployee = new javax.swing.JTable();
        jPanel55 = new javax.swing.JPanel();
        taddress = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel236 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        tphone = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jLabel241 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jLabel242 = new javax.swing.JLabel();
        tposition = new javax.swing.JComboBox<>();
        tid = new javax.swing.JTextField();
        jLabel243 = new javax.swing.JLabel();
        tbirthday = new com.toedter.calendar.JDateChooser();
        tgenderfemale = new javax.swing.JRadioButton();
        tgendermale = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel244 = new javax.swing.JLabel();
        searchposition = new javax.swing.JComboBox<>();
        jLabel245 = new javax.swing.JLabel();
        searchaddress = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuBanHang = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jCheckBox1.setText("jCheckBox1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(999, 600));

        jPanel56.setBackground(new java.awt.Color(255, 255, 255));

        jPanel57.setBackground(new java.awt.Color(153, 255, 153));

        jLabel246.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel246.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel246.setText("Danh Sách Thông Tin Nhân Viên");

        tableemployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tableemployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Họ Tên", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "Số Điện Thoại", "Email", "Chức Vụ"
            }
        ));
        tableemployee.setRowHeight(40);
        tableemployee.setShowGrid(true);
        tableemployee.setSurrendersFocusOnKeystroke(true);
        tableemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableemployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableemployee);

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel246)
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel57Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel246)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel55.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhân Viên"));

        add.setBackground(new java.awt.Color(153, 255, 255));
        add.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        add.setText("Thêm");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel236.setText("Ngày Sinh: ");

        delete.setBackground(new java.awt.Color(153, 255, 255));
        delete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        delete.setText("Xóa");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(153, 255, 255));
        update.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        update.setText("Cập nhật");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel237.setText("Mã Nhân Viên: ");

        jLabel238.setText("Tên Nhân Viên: ");

        jLabel239.setText("Địa Chỉ: ");

        jLabel240.setText("Số điện thoại: ");

        jLabel241.setText("Chức Vụ: ");

        jLabel242.setText("Giới Tính");

        tposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giám đốc", "Trưởng Phòng", "Nhân Viên" }));

        jLabel243.setText("Email: ");

        tbirthday.setDateFormatString("dd-MM-yyyy");

        buttonGroup1.add(tgenderfemale);
        tgenderfemale.setText("Nữ");

        buttonGroup1.add(tgendermale);
        tgendermale.setText("Nam");
        tgendermale.setToolTipText("");

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel241)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(10, 10, 10)))
                .addGap(29, 29, 29)
                .addComponent(tposition, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel238))
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel236)
                            .addComponent(jLabel237)
                            .addComponent(jLabel242))))
                .addGap(23, 23, 23)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(tid, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(34, 34, 34))
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel55Layout.createSequentialGroup()
                                        .addComponent(tgendermale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tgenderfemale))
                                    .addGroup(jPanel55Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(update)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addComponent(jLabel239)
                                .addGap(42, 42, 42)
                                .addComponent(taddress))
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel243)
                                    .addComponent(jLabel240))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel55Layout.createSequentialGroup()
                                        .addComponent(tphone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 6, Short.MAX_VALUE))
                                    .addComponent(temail)))
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(delete)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addComponent(tbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel241)
                    .addComponent(tposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel237)
                    .addComponent(jLabel239)
                    .addComponent(taddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel238)
                    .addComponent(jLabel240)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel243)
                    .addComponent(jLabel242)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgenderfemale)
                    .addComponent(tgendermale))
                .addGap(18, 18, 18)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel236)
                    .addComponent(tbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(delete))
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update)
                            .addComponent(add))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel244.setText("Tìm Kiếm theo chức vụ: ");

        searchposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giám đốc", "Trưởng Phòng", "Nhân Viên" }));
        searchposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchpositionActionPerformed(evt);
            }
        });

        jLabel245.setText("Tìm kiếm theo địa chỉ: ");

        search.setBackground(new java.awt.Color(153, 255, 255));
        search.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        search.setText("Tìm ");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(153, 255, 255));
        cancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset.png"))); // NOI18N
        cancel.setText("Hủy");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel245)
                                .addComponent(searchposition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel244))
                            .addComponent(searchaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(search)
                        .addGap(52, 52, 52)
                        .addComponent(cancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel244)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchposition, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel245)
                .addGap(18, 18, 18)
                .addComponent(searchaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search)
                    .addComponent(cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuBanHang.setText("Quản Lý");

        jMenuItem2.setText("Tài Khoản");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuBanHang.add(jMenuItem2);

        jMenuItem7.setText("Lương nhân viên");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        MenuBanHang.add(jMenuItem7);

        jMenuBar1.add(MenuBanHang);

        jMenu6.setText("Báo Cáo");
        jMenuBar1.add(jMenu6);

        jMenu2.setText("Thoát");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void DisplayTable(){
        try{
            st = con.createStatement();
            rs = st.executeQuery("Select * from customermanagement");
            tableemployee.setModel(DbUtils.resultSetToTableModel(rs));
            String[] header = {"Mã nhân viên","Họ tên","Giới tính","Ngày sinh","Địa chỉ","Số điện thoại","Email","Chức vụ"};
            TableColumnModel tcm = (TableColumnModel)tableemployee.getColumnModel();
            for(int i=0; i<header.length; i++){
                TableColumn title = tcm.getColumn(i);
                title.setHeaderValue(header[i]);
            }
            tableemployee.getTableHeader().repaint();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here
        if(tid.getText().isEmpty() || tname.getText().isEmpty() || buttonGroup1.getSelection() == null || tbirthday.getDate() == null || taddress.getText().isEmpty() || tphone.getText().isEmpty() || temail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Dữ liệu không được để trống", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            try{
                if(this.con != null){
                ps = con.prepareStatement("insert into customermanagement values (?, ?, ?, ?, ?, ?, ?, ?)");
                ps.setString(1, tid.getText());
                ps.setString(2, tname.getText());
                if (tgendermale.isSelected()) {
                    ps.setString(3, "Nam");
                } else if (tgenderfemale.isSelected()) {
                    ps.setString(3, "Nữ");
                }
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String birthdateString = dateFormat.format(tbirthday.getDate());
                ps.setString(4, birthdateString);
                ps.setString(5, taddress.getText());
                ps.setString(6, tphone.getText());
                ps.setString(7, temail.getText());
                ps.setString(8, tposition.getSelectedItem().toString());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                DisplayTable();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Lỗi", "Thông Báo", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         if(tid.getText().isEmpty() || tname.getText().isEmpty() || buttonGroup1.getSelection() == null || tbirthday.getDate() == null || taddress.getText().isEmpty() || tphone.getText().isEmpty() || temail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Dữ liệu không được để trống", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            try{
                if(this.con != null){
                String gender = "";
                if(tgendermale.isSelected()){
                    gender += "Nam";
                }
                else{
                    gender += "Nữ";
                }
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String birthdateString = dateFormat.format(tbirthday.getDate());
                String query = "update customermanagement set TenNV='" + tname.getText() + "' " +
                                                                         ",GioiTinh='" + gender + "' " +
                                                                         ",NgaySinh='" + birthdateString + "' " +
                                                                         ",DiaChi='" + taddress.getText() + "'" +
                                                                         ",SoDienThoai='" + tphone.getText() + "' " +
                                                                         ",Email='" + temail.getText() + "' " +
                                                                         ",ChucVu='" + tposition.getSelectedItem() + "' " +
                                                                         "where MaNV = '"+ tid.getText()+"'";
                        
                ps = con.prepareStatement(query);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                DisplayTable();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Lỗi", "Thông Báo", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            String query = "delete from customermanagement where MaNV='" + tid.getText()+ "'";
            ps = con.prepareStatement(query);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            DisplayTable();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void searchpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchpositionActionPerformed
        // TODO add your handling code here:
        try{
            String query = "Select * from customermanagement where ChucVu ='" + searchposition.getSelectedItem()+ "'";
            st = con.createStatement();
            rs = st.executeQuery(query);
            if(!rs.isBeforeFirst()){
                JOptionPane.showMessageDialog(this, "Không có nhân viên nào giữ chức vụ này!");
                DisplayTable();
            }
            else{
                JOptionPane.showMessageDialog(this, "Tìm thành công");
                tableemployee.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchpositionActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        if(searchaddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập dữ liệu", "Thông Báo", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                String query = "Select * from customermanagement where DiaChi='"+ searchaddress.getText()+"'";
                st = con.createStatement();
                rs = st.executeQuery(query);
                if(!rs.isBeforeFirst()){
                    JOptionPane.showMessageDialog(this, "Không có nhân viên nào ở " + searchaddress.getText(), "Thông Báo", JOptionPane.ERROR_MESSAGE);
                    DisplayTable();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Tìm thành công");
                    tableemployee.setModel(DbUtils.resultSetToTableModel(rs));
            }
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchMouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new QL_Salary().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void tableemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableemployeeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tableemployee.getModel();
        // getSelectedRow(): lấy chỉ mục của hàng đang được chọn
        int data = tableemployee.getSelectedRow();
        tid.setText(dtm.getValueAt(data, 0).toString());
        tname.setText(dtm.getValueAt(data, 1).toString());
        if(dtm.getValueAt(data, 2).toString().equals("Nam")){
            tgendermale.setSelected(true);
            tgenderfemale.setSelected(false);
        }
        else if(dtm.getValueAt(data, 2).toString().equals("Nữ")){
            tgenderfemale.setSelected(true);
            tgendermale.setSelected(false);
        }

        //SimpleDateFormat dateformnat = new SimpleDateFormat()
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            java.util.Date date = (java.util.Date)dateFormat.parse(dtm.getValueAt(data, 3).toString());
            tbirthday.setDate(date);
        } catch (Exception e) {
            e.printStackTrace();
        }
        taddress.setText(dtm.getValueAt(data,4).toString());
        tphone.setText(dtm.getValueAt(data, 5).toString());
        temail.setText(dtm.getValueAt(data, 6).toString());
        tposition.setSelectedItem(dtm.getValueAt(data, 7).toString());
    }//GEN-LAST:event_tableemployeeMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new QL_TaiKhoan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        new HomeManager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBanHang;
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel246;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchaddress;
    private javax.swing.JComboBox<String> searchposition;
    private javax.swing.JTable tableemployee;
    private javax.swing.JTextField taddress;
    private com.toedter.calendar.JDateChooser tbirthday;
    private javax.swing.JTextField temail;
    private javax.swing.JRadioButton tgenderfemale;
    private javax.swing.JRadioButton tgendermale;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tphone;
    private javax.swing.JComboBox<String> tposition;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
